/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public void anotherMethod() {
        // do nothing
    }
    public void yetAnotherMethod() {
        // do nothing
    }
}
